### ISSUE TITLE
Support Testnet

### ISSUE THREAD

**Issue by Giszmo** [JornC/bitcoin-transaction-explorer#14]
I installed it on [my own server](http://leo.jochen-hoenicke.de:8080/bitcoin-transactions-server-0.1/#block:last) but was very disappointed when I found no testnet option in the config as I wanted to interpret testnet stuff and didn't find a running instance for testnet.

(Also it didn't ask me anything about my bitcoin server and didn't complain even though it obviously has issues connecting to the server. There are both testnet and mainnet running on the machine.)

**Comment by JornC** [comment]
Testnet (and other chains) work out of the box so long as the bitcoind instance uses a compatible JSON-RPC interface, just instead of the default mainnet port, for testnet direct it to the testnet port instead; 18333

The lack of errors in case of trouble is indeed an issue.

**Comment by Giszmo** [comment]
ok, found it. the connector was set to "bitcoin core node", which was fine, so I didn't touch the dropdown and didn't get all the other fancy options.
