### ISSUE TITLE
BUILD FAILURE  Check that your module inherits 'com.google.gwt.core.Core' either directly or indirectly (most often by inheriting module 'com.google.gwt.user.User')

### ISSUE THREAD

**Issue by alessandro-aglietti** [JornC/bitcoin-transaction-explorer#24]
Hi,
this blockchain reader is awesome!!

I'm trying to bring it up but with `mvn install` I receive

![image](https://user-images.githubusercontent.com/638619/104253939-f730a800-5475-11eb-9c01-f3a88e39b8c8.png)

I've try to use `mvn -X install` but didn't show up any useful error messages.

Any suggestion on how to build it @JornC ?

Thank you very much,

**Comment by JornC** [comment]
Hello @alessandro-aglietti 

I believe the explorer can't be built with JDK 11 (it's been a while), needs to be JDK 8 to work.

But wait! I've recently started work on a new version of this explorer to resolve some of the current version's many flaws:

https://github.com/yogh-io/bitcoin-yogh-explorer (see at https://beta.yogh.io/), which does work with JDK 11 -- that version is probably easier to get up and running (see the `serve.sh` script for example if you're running some flavour of Linux)

**Comment by alessandro-aglietti** [comment]
Yeahh, it works @JornC:

I use a docker compose https://github.com/bitcoin-dalla-teoria-alla-pratica/bitcoin-in-action-playground/blob/master/docker-compose.yml#L68-L78 for regtest debug purpose!

Thank you very much,
